import * as m from "zigbee-herdsman-converters/lib/modernExtend";

export default {
    zigbeeModel: ["ZigbeePoolSensorsCalib"],
    model: "ZigbeePoolSensorsCalib",
    vendor: "Bulcke",
    description: "Automatically generated definition",
    extend: [
        m.deviceEndpoints({endpoints: {4: 4, 5: 5, 6: 6, 9: 9, 10: 10, 11: 11, 12: 12}}),
        m.numeric({
            name: "pH",
            unit: "pH",
            cluster: "genAnalogInput",
            attribute: "presentValue",
            reporting: {min: "MIN", max: "MAX", change: 1},
            description: "Mesure pH",
            access: "STATE_GET",
            endpointNames: ["9"],
           precision: 2,
        }),
        m.numeric({
            name: "ORP",
            unit: "mV",
            cluster: "genAnalogInput",
            attribute: "presentValue",
            reporting: {min: "MIN", max: "MAX", change: 1},
            description: "mesure ORP",
            access: "STATE_GET",
            endpointNames: ["12"],
            precision: 2,
        }),
        m.temperature({endpointNames: ["10"]}),
        m.pressure({endpointNames: ["11"]}),
        m.numeric({
            name: "bar",
            unit: "bar",
            cluster: "msPressureMeasurement",
            attribute: "measuredValue",
            description: "Pressure in bar",
            scale: 1000,
            precision: 2,
            access: "STATE",
        }),
        m.binary({
            name: "PH401 Calibration",
            cluster: "genBinaryOutput",
            attribute: "presentValue",
            reporting: {attribute: "presentValue", min: "MIN", max: "MAX", change: 1},
            valueOn: ["ON", 1],
            valueOff: ["OFF", 0],
            description: "Calibration avec solution pH 4.01",
            access: "ALL",
            endpointName: "4",
        }),
        m.binary({
            name: "PH700 Calibration",
            cluster: "genBinaryOutput",
            attribute: "presentValue",
            reporting: {attribute: "presentValue", min: "MIN", max: "MAX", change: 1},
            valueOn: ["ON", 1],
            valueOff: ["OFF", 0],
            description: "Calibration avec solution pH 7.00",
            access: "ALL",
            endpointName: "5",
        }),
        m.binary({
            name: "ORP256 Calibration",
            cluster: "genBinaryOutput",
            attribute: "presentValue",
            reporting: {attribute: "presentValue", min: "MIN", max: "MAX", change: 1},
            valueOn: ["ON", 1],
            valueOff: ["OFF", 0],
            description: "Calibration avec solution ORP 256mV",
            access: "ALL",
            endpointName: "6",
        }),
    ],
    meta: {multiEndpoint: true},
};
